# Define the desired name and path to a directory containing a Cargo.toml for each extension plugin.
# Extension plugin names must start with `reaper_` or they will not be recognized by REAPER.

[extension_plugins]
reaper_ext_0 = "src/extension_0"
reaper_ext_1 = "src/extension_1"
reaper_ext_2 = "src/extension_2"
