name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cloud-scythe-labs.cachix.org
            extra-trusted-public-keys = cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw=

      - name: Build Docs
        run: nix develop -c mdbook build docs

      - name: Copy favicons
        run: |
          cp assets/rea-corro.svg docs/book/favicon.svg
          cp assets/favicon.png docs/book/favicon.png

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
