name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Docs
        run: nix-shell -p mdbook --run "mdbook build docs"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
