name: Nix Build
on:
  workflow_call:
jobs:
  nix-build:
    name: Nix Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://cloud-scythe-labs.cachix.org
            extra-trusted-public-keys = cloud-scythe-labs.cachix.org-1:I+IM+x2gGlmNjUMZOsyHJpxIzmAi7XhZNmTVijGjsLw=
            extra-experimental-features = nix-command flakes auto-allocate-uids cgroups
            auto-allocate-uids = true
            use-cgroups = true
            extra-system-features = uid-range
      - name: Build cargo-reaper
        run: nix-build
      - name: Build checks
        run: nix-build release.nix -A checks --keep-going
      - name: Build NixOS tests
        if: matrix.os == 'ubuntu-latest'
        run: nix-build release.nix -A nixosTests --keep-going
      - name: Build Windows cross check
        if: matrix.os == 'ubuntu-latest'
        run: nix-build release.nix -A crossChecks --keep-going
